#------------------------------
# GitHub Action Part-1
#------------------------------

name: My-Project

on:
  push:
    branches: [ main ]

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello Message in Testing
        run: echo "Hello from Testing job"

  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]

    steps:
      - name: Print Hello Message in Deploy
        run: echo "Hello from Deploy job"
