#------------------------------
# GitHub Action Part-1
#------------------------------

name: My-Project
env :
  APPLICATION_NAME    : "PasswordGenerator"
  DEPLOY_PACKAGE_NAME : "pg-deploy-ver-${{ github.sha }}"

on:
  push:
    branches: [ main ]

jobs:
  my_testing:
    runs-on : windows-latest

    steps:       
      - name: Greeting
        run : |
          echo "Welcome"
          echo "Application name: ${{ env.APPLICATION_NAME }}"
          
      - name: Lets test g++
        run : g++ --version
        
      - name: Lets test make for Windows
        run : mingw32-make --version 
        
      - name: Git clone my repo
        uses: actions/checkout@v1
        
      - name: Build application
        run: mingw32-make
