#------------------------------
# GitHub Action Part-1
#------------------------------

name: My-Project

on:
  push:
    branches: [ main ]

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello Message
        run: echo "Hello from Testing job"

  my_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello Message
        run: echo "Hello from Deploy job"
